[build]
  # Команда для сборки
  command = "npm run build"
  
  # Папка с собранными файлами
  publish = "dist"

[build.environment]
  # Версия Node.js
  NODE_VERSION = "18"

# Перенаправления для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Заголовки безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Заголовки для статических файлов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Настройки для Web Bluetooth API
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "bluetooth=()"
    Feature-Policy = "bluetooth 'self'"
